telegram:
  token: "BOT_TOKEN_DARI_BOTFATHER"

cloudflare:
  email: "EMAIL_AKUN_CLOUDFLARE"
  api_key: "GLOBAL_API_KEY_CLOUDFLARE"

whitelist:
  - 123456789
  - 987654321

domains:
  - name: "301maha.store"
    zone_id: "ZONE_ID"
    type: "redirect_rules"
    ruleset_id: "RULESET_ID"
    rule_id: "RULE_ID"
  - name: "maha301.lol"
    zone_id: "ZONE_ID"
    type: "redirect_rules"
    ruleset_id: "RULESET_ID"
    rule_id: "RULE_ID"
  - name: "maha55.id"
    zone_id: "ZONE_ID"
    type: "redirect_rules"
    ruleset_id: "RULESET_ID"
    rule_id: "RULE_ID"
  - name: "maha66.id"
    zone_id: "ZONE_ID"
    type: "redirect_rules"
    ruleset_id: "RULESET_ID"
    rule_id: "RULE_ID"
  - name: "mh301sl.store"
    zone_id: "ZONE_ID"
    type: "page_rules"
    rule_id: "RULE_ID"
